config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :products, only: [:index, :show]
end

app/models/builder/gsm_arena.rb
class Builder::GSMArena

  def build_item(document)
    name = document.at_css('h1').text

    image_url = document.at_css('.specs-photo-main img')&.get('src')

    specs = document.css('#specs-list table').map do |spec|
      spec_name = spec.at_css('th').text

      categories = spec.css('tr').map do |sc|
        OpenStruct.new(name: sc.at_css('.ttl')&.text, values: sc.at_css('.nfo')&.text)
      end

      OpenStruct.new(name: spec_name, categories: categories)
    end

    Product.new(name: name, image_url: image_url, specs: specs)
  end

  def build_list(document)
    document.css('.makers ul li a').map do |phone|
      name = phone.at_css('strong span').children.map(&:text).reject(&:empty?).join(' ')

      link = 'gsm_arena_' + phone.get('href')

      image_url = phone.at_css('img').get('src')

      Product.new(name: name, image_url: image_url, link: link)
    end
  end
end

app/models/caller.rb
class Caller

  def get(path)
    response = client.get_response(item_uri(path))
    return if response.code.to_i > 400

    document = parser.parse_html(response.body)
    builder.build_item(document)
  end

  def search(query)
    response = client.get_response(search_uri(query))
    document = parser.parse_html(response.body)

    builder.build_list(document)
  end

  private

  def client
    Net::HTTP
  end

  def parser
    Oga
  end

end

app/models/caller/gsm_arena.rb
class Caller::GSMArena < Caller

  URL = 'http://www.gsmarena.com/'

  private

  def builder
    Builder::GSMArena.new
  end

  def normalize(path)
    normalized_path = path.end_with?('.php') ? path : "#{path}.php"
    normalized_path.gsub('gsm_arena_', '')
  end

  def item_uri(path)
    URI.parse(URL + normalize(path))
  end

  def search_uri(query)
    URI.parse(URL + 'results.php3?sQuickSearch=yes&sName=' + query.to_s)
  end

end

app/models/caller/null.rb
class Caller::Null

  def get(path)
    nil
  end

  def search(query)
    []
  end
end

app/models/fetcher.rb
class Fetcher

  attr_reader :callers

  def initialize(callers: [Caller::GSMArena.new])
    @callers = callers
  end

  def get(path)
    caller = caller_for(path) || Caller::Null.new
    caller.get(path)
  end

  def search(query)
    callers.map { |caller| caller.search(query) }.flatten
  end

  private

  def caller_for(path)
    if path.start_with?('gsm_arena_')
      callers.find{|c| c.is_a?(Caller::GSMArena)}
    end
  end
end

app/models/product.rb
class Product
  attr_reader :name, :image_url, :specs, :link

  def initialize(name:, image_url: '', link: nil, specs: [])
    @name      = name
    @image_url = image_url
    @link      = link
    @specs     = specs
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @query = params[:search]
    @products = fetcher.search(@query)
  end

  def show
    @product = fetcher.get(params[:id])
    @product || head(:not_found)
  end

  private

  def fetcher
    Fetcher.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<section id="searchForm">
  <header class="text-xs-center h1">GSM Scanner</header>
  <%= form_tag products_path, class: 'form-inline text-xs-center', method: :get, remote: true do %>
    <div class="form-group">
      <%= label_tag :search, 'Phone finder' %>
      <%= text_field_tag :search, params[:search], autofocus: true, placeholder: 'ASUS Zenfone', class: 'form-control' %>
    </div>
    <%= submit_tag 'Search', class: 'btn btn-primary' %>
  <% end %>
</section>
<div id="mainWrapper"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GSM Arena on Rails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_not_found.html.erb
<div class="alert alert-info" role="alert">
  <strong><%= @query %></strong> not found
</div>

app/views/products/_product.html.erb
<div class="container" style="margin-top: 20px">
  <%= image_tag product.image_url, style: 'float: right' %>
  <h1><%= product.name %></h1>
  <% product.specs.each do |spec| %>
    <h2><%= spec.name %></h2>
    <table class="table" style="width: 80%">
      <% spec.categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td><%= category.values %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>

app/views/products/_product_preview.html.erb
<%= link_to "products/#{product.link}", class: 'card', remote: true do %>
  <div class="card-block text-xs-center">
      <%= image_tag product.image_url, alt: product.name %>
    <h5>
      <%= product.name %>
    </h5>
  </div>

<% end %>

app/views/products/index.js.erb
$('#mainWrapper').html('<div id="products"></div>');
<% if @products.present? %>
$('#products').append('<%= j render(partial: 'product_preview', collection: @products, as: 'product') %>');
<% else %>
$('#products').append('<%= j render('not_found') %>');
<% end %>

app/views/products/show.js.erb
$('#mainWrapper').html('<%= j render('product', product: @product) %>');